@WebApiCaching_HostAddress = https://localhost:7002

GET {{WebApiCaching_HostAddress}}/api/Jogador/BuscarJogadores/
Accept: application/json

###
GET {{WebApiCaching_HostAddress}}/api/Jogador/BuscarJogadorId/11
Accept: application/json
###

DELETE {{WebApiCaching_HostAddress}}/api/Jogador/DeletarJogadorId/11
Accept: application/json
###
