# @WebApiCaching_HostAddress = http://localhost:5148
@WebApiCaching_HostAddress = https://localhost:7002

GET {{WebApiCaching_HostAddress}}/api/Jogador/
Accept: application/json

###
GET {{WebApiCaching_HostAddress}}/api/Jogador/1
Accept: application/json
###
GET {{WebApiCaching_HostAddress}}/api/Jogador/2
Accept: application/json
###

GET {{WebApiCaching_HostAddress}}/api/Jogador/4
Accept: application/json
###
DELETE {{WebApiCaching_HostAddress}}/api/Jogador/15
Accept: application/json
###